---
title: "Tarea 2"
subtitle: "EYP3407 - Tópicos Aplicados en estadística"
author: 
    - Camila Echeverría
    - Francisca Vilca
format:
    html:
        code-fold: false
        embed-resources: true
        toc: true
        toc-title: "Contenidos"
---

## Pregunta 1

## Pregunta 2

```{r}
#| message: false
#| warning: false

library(ISLR)
library(dplyr)
library(rio)
library(leaps)
library(glmnet)
library(caret)
```

```{r}
datos <- Hitters

str(datos)
summary(datos)

datos <- na.omit(datos)
datos$Salary <- log(datos$Salary)
```


### a)

Regresión Lasso

```{r}
x <- model.matrix(Salary ~., datos)[,-1]
y <- datos$Salary

grilla <- 10^seq(10, -2, length = 100)

set.seed(3312)

mod_lasso <- glmnet(x, y, alpha = 1, lambda = grilla)

cv_lasso <- cv.glmnet(x, y, alpha = 1)
lambda <- cv_lasso$lambda.min #0.003980233

lasso_2.0 <- predict(mod_lasso, type = "coefficients", s = lambda)

round(lasso_2.0, 4)
```

Regresión Ridge

```{r}
mod_ridge <- glmnet(x, y, alpha = 0, lambda = grilla)

cv_ridge <- cv.glmnet(x, y, alpha = 0)
lambda <- cv_ridge$lambda.min #0.0551217

ridge_2.0 <- predict(mod_ridge, type = "coefficients", s = lambda)

round(ridge_2.0, 4)
```

Elastic-Net

```{r}
library(caret)

cv_5 <-  trainControl(method = "cv", number = 5)

hit_elnet <-  train(
  Salary ~ ., data = datos,
  method = "glmnet",
  trControl = cv_5
)

hit_elnet$bestTune

mod_elnet <- glmnet(x, y, 
                    alpha = hit_elnet$bestTune[1],
                    lambda = as.numeric(hit_elnet$bestTune[2]))

cv_elnet <- cv.glmnet(x, y, alpha = hit_elnet$bestTune[1])
lambda <- cv_elnet$lambda.min #0.1215506

elnet_2.0 <- predict(mod_elnet, type = "coefficients", s = lambda)

round(elnet_2.0, 4)
```

Lasso Adaptativo

```{r}
peso <- 1/abs(matrix(coef(
  cv_ridge, s=cv_ridge$lambda.min)[, 1][2:(ncol(x)+1)] ))^1 #Gamma=1

mod_lassopro <- glmnet(x, y, alpha = 1, penalty.factor = peso)

cv_lassopro <- cv.glmnet(x, y, alpha = 1, penalty.factor = peso)

lambda <- cv_lassopro$lambda.min #0.1215506

lassopro_2.0 <- predict(mod_lassopro, type = "coefficients", s = lambda)

round(lassopro_2.0, 4)
```

### b)

